title:        Magnetic Jargon
url:          http://developer.apis.how
version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/news/page:num"

production_url : http://developer.magnetic.jargon.kinlane.com

BASE_PATH : http://developer.magnetic.jargon.kinlane.com

org: kinlane
repo: magnetic.jargon
resource: dictionary
oauthio: qUDL4eZqKPFb41SwuWIYIwLR6jI
